### ISSUE TITLE
[Bug] Satan's Contract has no costume

### ISSUE THREAD

**Issue by Meowlala** [FacemanFoothand/GroupAlpha#14]
Grants flight but no wings, causing Isaac to do his walking animation forever.
Solution is to either make a new costume for this item or reuse an old one like Lord of the Pit

**Comment by mikemedina** [comment]
I'm changing the label here since it's not really broken, we just don't have the art yet. There has been some proposed art in the #general channel which looks great!

**Comment by FacemanFoothand** [comment]
removed the issue as satan's contract item has been outlined in another issue
